function eql_plot_res_ex2(varargin)
    %% *SET-UP*
    inp = varargin{1};
    out = varargin{2};
    set(0,'defaultaxescolororder',[1 0 0;0 0 1]);
    %
    xlm.thv = [0,50];
    [xtk.thv,~] = get_axis_tick(xlm.thv,xlm.thv,5,1);
    ylm.thv = [-0.060;0.060];
    ytk.thv = -0.060:0.03:0.060;
    %
    xlm.fsv = [1e-1;25];
    xtk.fsv = [1e-1;1e0;1e1;25];
    ylm.fsv = [1e-6;1e-1];
    ytk.fsv = [1e-6;1e-3;1e-1];
    
    [out.vfr,out.fsv(1,:)] = super_fft(mean(diff(out.vtm)),out.thv(1,:),0,[1,2]);
    [out.vfr,out.fsv(2,:)] = super_fft(mean(diff(out.vtm)),out.thv(end,:),0,[1,2]);
    
    %% *PLOT INPUT MOTION*
    % time-histories
    fpplot('xpl',{out.vtm},'ypl',{out.thv(end,:)},...
        'vfg','on','pfg',[0,0,14,5.75],'leg',{{'eql'}},'lst',{'-'},'lwd',3,...
        'xlm',{xlm.thv},'xtk',{xtk.thv},'ylm',{ylm.thv},'ytk',{ytk.thv},...
        'tit',{'G.L. -83m'},...
        'xlb',{'t [s]'},'ylb',{'v(t) [m/s]'});
    % fourier's spectra
    fpplot('xpl',{out.vfr},'ypl',{out.fsv(end,:)},...
        'vfg','on','pfg',[0,0,12,12],'leg',{{'eql'}},'lst',{'-'},'lwd',3,...
        'xlm',{xlm.fsv},'xtk',{xtk.fsv},'ylm',{ylm.fsv},'ytk',{ytk.fsv},...
        'tit',{'G.L. -83m'},'scl',{'log'},...
        'xlb',{'f [Hz]'},'ylb',{'FSV [m]'});
    
    %% *PLOT OUTPUT MOTION*
    data = importdata('thv_volvi_nl_weak_surface.txt');
    nln.vtm.srf = data(:,1);
    nln.thv.srf = data(:,2);
    nln.tha.srf = [0;diff(nln.thv.srf)./mean(diff(nln.vtm.srf))];
    [nln.vfr.srf,nln.fsv.srf] = super_fft(mean(diff(nln.vtm.srf)),nln.thv.srf,0,[1,2]);

    % time-histories
    fpplot('xpl',{out.vtm},'ypl',{out.thv(1,:)},...
        'vfg','on','pfg',[0,0,14,5.75],'leg',{{'eql'}},'lst',{'-'},'lwd',3,...
        'xlm',{xlm.thv},'xtk',{xtk.thv},'ylm',{ylm.thv},'ytk',{ytk.thv},...
        'tit',{'G.L. 0m'},...
        'xlb',{'t [s]'},'ylb',{'v(t) [m/s]'});
    % fourier's spectra
    fpplot('xpl',{out.vfr},'ypl',{out.fsv(1,:)},...
        'vfg','on','pfg',[0,0,12,12],'leg',{{'eql'}},'lst',{'-'},'lwd',3,...
        'xlm',{xlm.fsv},'xtk',{xtk.fsv},'ylm',{ylm.fsv},'ytk',{ytk.fsv},...
        'tit',{'G.L. 0m'},'scl',{'log'},...
        'xlb',{'f [Hz]'},'ylb',{'FSV [m]'});
    
    %% *PLOT EBHSR MOTION*
    out.bsr = spectral_ratio(out.vtm,out.tha(1,:),out.vtm,out.tha(end,:),0.1,4);
   
    % fourier's spectra
    fpplot('xpl',{out.bsr(1,:)},'ypl',{abs(out.bsr(2,:))},...
        'vfg','on','pfg',[0,0,12,12],'leg',{,'eql'},'lst',{'-'},'lwd',3,...
        'xlm',{xlm.fsv},'xtk',{xtk.fsv},'ylm',{[1,1e3]},'ytk',{[1,1e1,1e2,1e3]},...
        'tit',{'G.L. 0m/G.L. -83m'},'scl',{'log'},...
        'xlb',{'f [Hz]'},'ylb',{'BHSR [1]'});
    return
end

